version: "3.9"
services:
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8080"

  frontend:
    container_name: frontend
    build: ./frontend/
    volumes:
      - frontend-build:/frontend/dist

  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - frontend-build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  frontend-build:
