apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: frontend-build
          emptyDir: {}
      containers:
        - name: frontend
          image: nellshark/mock-api-hub-frontend
          lifecycle:
            postStart:
              exec:
                command: ["cp", "-r", "/frontend/dist/.", "/build"]
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]    
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: frontend-build
              mountPath: /build

        - name: nginx
          image: nginx:1.25.2-alpine-slim
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: frontend-build
              mountPath: /usr/share/nginx/html
